### ISSUE TITLE
"Directory" is not accessible under System.IO.Directory?

### ISSUE THREAD

**Issue by AndyCYao** [lobstermobster/AndroidSchedulerApp#4]
From looking online i saw the best way to retrieve a list of files in a folder is this line:

string [] fileEntries = Directory.GetFiles(targetDirectory);

But i can't seem to access Directory in the utility.cs right now, is it because I have not declared the right namespace or something? 

I am doing this so that I can find all the ringtone .midi files in the ringtone folder.

**Comment by plu83** [comment]
If this is being done within the PCL, remember that you need to use the PCLStorage API for a platform agnostic means of viewing a folder's contents.

I'm willing to bet that the default ringtone folder location for each platform (assuming they all have one) will be different though. So you would likely need to define a common ringtone enumeration interface which each platform's project would have an implementation of. As this project is called the "AndroidSchedulerApp", I think it'd be fine if you only implemented the call for the Android project.

**Comment by AndyCYao** [comment]
I tried using the recommended way to retrieving folder via PCLStorage, that is, start with the rootfolder of FileSystem.Current.LocalStorage and then find your subfolder from there , in our case ringtone.

but the FileSystem.Current.LocalStorage returns a 
..\AppData\Local\Microsoft Corporation\Microsoft (R) Windows (R) Operating System\10.0.10052.0

rather than what i would expect the ..\SchedulerApp\ as root.
