### ISSUE TITLE
Do you guys see these bugs?

### ISSUE THREAD

**Issue by AndyCYao** [lobstermobster/AndroidSchedulerApp#5]
![capture](https://cloud.githubusercontent.com/assets/6835537/10781009/90ff8788-7d00-11e5-9dcf-5d2949053f9c.PNG)

do you guys see these bugs above? I have no idea how to handle it.

**Comment by plu83** [comment]
Right click the Solution, select "Restore NuGet Packages" and rebuild. That might resolve the matter. As you may recall, I downgraded my Xamarin libraries to something that I believe was newer than what was previously specified.

**Comment by AndyCYao** [comment]
Weird. i didn't downgrade or update anything , and today it seems to fixed itself. I can build without any errors ..

**Comment by AndyCYao** [comment]
Guys, I have a potential newbie question. 
Can you guys tell me why I can't access Android library on the right hand side (LocalRingTones) but in the left hand side (LocalNotification) I can?

AFAIK they are both using the same libraries. But on the left side, the intellisense has Android objects , but on the right there isn't. 

![capture](https://cloud.githubusercontent.com/assets/6835537/10872189/0ea3189a-80b1-11e5-9979-a813bacdec1f.PNG)
I have seen something like this before when I did VBA scripting. but before it had to with late binding vs. early binding.

**Comment by AndyCYao** [comment]
I figured it out.. it had to do with the right hand side being a "MIscellaneous File" rather than part of the Solution Explorer. Once the file was added and it became under ScheduleApp.Droid... the intellisense came back up
