### ISSUE TITLE
List tuple is not in an assembly that's referenced. must add reference to System Collection. 

### ISSUE THREAD

**Issue by AndyCYao** [lobstermobster/AndroidSchedulerApp#6]
Hi guys, im not understanding this error message. It says i must add System.Collection as a reference.. but i did that already right? on the top i have already declared System.Collection. 

![capture](https://cloud.githubusercontent.com/assets/6835537/11262821/b26523a8-8e38-11e5-8062-1a2d2e402cb8.PNG)

**Comment by AndyCYao** [comment]
i also pushed this as a separate branch so you guys can see see "RingtoneGetter" branch. could you let me know if you guys see this problem too?

**Comment by plu83** [comment]
That error message is referring to a Project Reference to System.Collection. I believe if you right click the ScheduleApp.Droid project, there'll be an option to manage references from which you can then select it.

**Comment by AndyCYao** [comment]
i see, ok i will try that tonight, i misunderstood the difference between the "using" and actually adding reference.
