### ISSUE TITLE
Is passing just one field in a struct possible?

### ISSUE THREAD

**Issue by AndyCYao** [lobstermobster/AndroidSchedulerApp#7]
Hey, is it possible to just pass one element of a structure? To set the default value in core config i need to pass the ringtone value to the defaultringtone in themestruct. See below

<img width="739" alt="screen shot 2016-01-24 at 11 38 43 pm" src="https://cloud.githubusercontent.com/assets/6835537/12545069/0df5692c-c2f4-11e5-9155-7a10ddb0d64d.png">

Is that error msg. function evaluation time out saying I cant be doing this?

Andy

**Comment by plu83** [comment]
I'm fairly certain you can pass in a struct instance's member for modification. 

The value message for Result suggests that ring.LastPathSegment or intent.GetParcelableExtra timed out . Can you step into those function calls by any chance?

**Comment by AndyCYao** [comment]
I rebuilt the project just now, and while I dont see the function evaluation time out anymore, it also isn't saving the right thing into the core.defaultringtone. I suspect I might have to alter the defaultringtone to something that houses an android uri object

**Comment by AndyCYao** [comment]
from looking at similar projects as we are doing here

https://github.com/seangrandini/multi-platform-project/blob/ab2f7873ce52ad7d42718ee7f9c965ec5a6fac79/alertApp/alertApp/alertApp/sharedLogic.cs

actual android media addresses are not saved in string paths but rather URIs. and URIs needs to be deconstructed using URI.Builder, so we would need to include using Android.Media in AppConfig for this to work, but when i add it its not recognizing android media.. I am so done with xamarin sheesh.

**Comment by plu83** [comment]
Keep in mind AppConfig exists in the ScheduleApp (Portable) project, so you would need to add an appropriate project reference to get Android.Media to be recognized. However, you shouldn't have to do that for a URI and shouldn't in general since ScheduleApp Portable is where the platform agnostic common core logic resides.
